#ifndef MDIO_CONFIG_H
#define MDIO_CONFIG_H

/* Configuration For PORTA Pins ==> Direction */
#define MDIO_PA0_A_DIR PRVATE_INPUT
#define MDIO_PA1_A_DIR PRVATE_INPUT
#define MDIO_PA2_A_DIR PRVATE_INPUT
#define MDIO_PA3_A_DIR PRVATE_INPUT
#define MDIO_PA4_A_DIR PRVATE_INPUT
#define MDIO_PA5_A_DIR PRVATE_INPUT
#define MDIO_PA6_A_DIR PRVATE_INPUT
#define MDIO_PA7_A_DIR PRVATE_INPUT

/* Configuration For PORTB Pins ==> Direction */
#define MDIO_PA0_B_DIR PRVATE_OUTPUT
#define MDIO_PA1_B_DIR PRVATE_OUTPUT
#define MDIO_PA2_B_DIR PRVATE_OUTPUT
#define MDIO_PA3_B_DIR PRVATE_OUTPUT
#define MDIO_PA4_B_DIR PRVATE_OUTPUT
#define MDIO_PA5_B_DIR PRVATE_OUTPUT
#define MDIO_PA6_B_DIR PRVATE_OUTPUT
#define MDIO_PA7_B_DIR PRVATE_OUTPUT

/* Configuration For PORTC Pins ==> Direction */
#define MDIO_PA0_C_DIR PRVATE_OUTPUT
#define MDIO_PA1_C_DIR PRVATE_OUTPUT
#define MDIO_PA2_C_DIR PRVATE_OUTPUT
#define MDIO_PA3_C_DIR PRVATE_OUTPUT
#define MDIO_PA4_C_DIR PRVATE_OUTPUT
#define MDIO_PA5_C_DIR PRVATE_OUTPUT
#define MDIO_PA6_C_DIR PRVATE_OUTPUT
#define MDIO_PA7_C_DIR PRVATE_OUTPUT

/* Configuration For PORTD Pins ==> Direction */
#define MDIO_PA0_D_DIR PRVATE_OUTPUT
#define MDIO_PA1_D_DIR PRVATE_OUTPUT
#define MDIO_PA2_D_DIR PRVATE_OUTPUT
#define MDIO_PA3_D_DIR PRVATE_OUTPUT
#define MDIO_PA4_D_DIR PRVATE_OUTPUT
#define MDIO_PA5_D_DIR PRVATE_OUTPUT
#define MDIO_PA6_D_DIR PRVATE_OUTPUT
#define MDIO_PA7_D_DIR PRVATE_OUTPUT


/* Configuration For PORTA Pins ==> Values */
#define MDIO_PA0_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA1_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA2_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA3_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA4_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA5_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA6_A_INIT_VALUE PRIVATE_INPUT_FLOATING
#define MDIO_PA7_A_INIT_VALUE PRIVATE_INPUT_FLOATING

/* Configuration For PORTB Pins ==> Values */
#define MDIO_PA0_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA1_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA2_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA3_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA4_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA5_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA6_B_INIT_VALUE PRIVATE_LOW
#define MDIO_PA7_B_INIT_VALUE PRIVATE_LOW

/* Configuration For PORTC Pins ==> Values */
#define MDIO_PA0_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA1_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA2_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA3_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA4_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA5_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA6_C_INIT_VALUE PRIVATE_LOW
#define MDIO_PA7_C_INIT_VALUE PRIVATE_LOW

/* Configuration For PORTD Pins ==> Values */
#define MDIO_PA0_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA1_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA2_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA3_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA4_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA5_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA6_D_INIT_VALUE PRIVATE_LOW
#define MDIO_PA7_D_INIT_VALUE PRIVATE_LOW















#endif
